#!/bin/bash

deploy() {
  echo "> Deploy in progress..."
  terraform -chdir="./.terraform" plan
  terraform -chdir="./.terraform" apply
  main 1
}

uprade() {
  terraform -chdir="./.terraform" get
  terraform -chdir="./.terraform" init -upgrade
  main 1
}

ask() {
  choice=""
  read -p "> $1: " choice
  echo
}

main() {
  sleep $1
  echo "> Menu:
 ---|---------|-----------------------------------------------
  d | deploy  | Run plan and apply
 ---|---------|-----------------------------------------------
  u | upgrade | Get module and upgrade 
 ---|---------|-----------------------------------------------
  e | exit    | Stop the script
 ---|---------|-----------------------------------------------"
  ask "Enter your choice"
  while true; do
    case "$choice" in
    d)
      deploy
      break
      ;;
    u)
      uprade
      break
      ;;
    e)
      echo "> Byeee!"
      exit 0
      ;;
    *)
      echo "choice <- $choice"
      ask "Invalid choice. Enter your choice"
      ;;
    esac
  done
}

main 0
